name: Flutter Test and Build

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  test_android_ios:
    name: Test for Android and iOS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'  # Adjust Flutter version as needed
          channel: 'stable'   

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-cache-

      - name: Get packages
        run: flutter pub get

      - name: Run tests for Android
        run: flutter test

      - name: Run tests for iOS
        run: flutter test

  build_android:
    name: Build for Android
    runs-on: ubuntu-latest
    needs: test_android_ios

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'  # Adjust Flutter version as needed
          channel: 'stable'   

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-cache-

      - name: Get packages
        run: flutter pub get

      - name: Build APK for Android
        run: flutter build apk

      - name: Archive Android build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts-android
          path: build/app/outputs/apk/release/app-release.apk

  build_ios:
    name: Build for iOS
    runs-on: macos-latest
    needs: test_android_ios

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'  # Adjust Flutter version as needed
          channel: 'stable'   

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-cache-

      - name: Get packages
        run: flutter pub get

      - name: Build IPA for iOS
        run: flutter build ios

      - name: Archive iOS build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts-ios
          path: build/ios/...
